name: Continuous Integration

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Continuous Integration
    steps:
      - uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            2024/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('2024/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: cargo test
        working-directory: 2024
        run: cargo test
